function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

export function assembleReport(records) {
  const totalInstances = records.reduce(
    (sum, record) => sum + Number(record.instanceCount ?? 0),
    0,
  );
  const totalAlarms = records.reduce(
    (sum, record) => sum + Number(record.alarmCount ?? 0),
    0,
  );
  const statusCounts = records.reduce((counts, record) => {
    const status = record.status ?? "unknown";
    counts[status] = (counts[status] ?? 0) + 1;
    return counts;
  }, {});

  return {
    generatedAt: new Date().toISOString(),
    serviceCount: records.length,
    totalInstances,
    totalAlarms,
    statusCounts,
    records,
  };
}

export function renderBarChart(records, chartConfig) {
  const width = 920;
  const rowHeight = 52;
  const margin = { top: 72, right: 60, bottom: 48, left: 230 };
  const height =
    margin.top + margin.bottom + Math.max(records.length, 1) * rowHeight;
  const chartWidth = width - margin.left - margin.right;
  const values = records.map((record) =>
    Number(record[chartConfig.valueField] ?? 0),
  );
  const maxValue = Math.max(...values, 1);

  const rows = records
    .map((record, index) => {
      const label = record[chartConfig.categoryField] ?? `记录 ${index + 1}`;
      const value = values[index];
      const y = margin.top + index * rowHeight;
      const barWidth = Math.round((value / maxValue) * chartWidth);
      const color = value > 0 ? "#c4473a" : "#23856d";
      return `
  <text x="${margin.left - 14}" y="${y + 24}" text-anchor="end" font-size="15" fill="#243044">${escapeXml(label)}</text>
  <rect x="${margin.left}" y="${y + 8}" width="${chartWidth}" height="26" rx="3" fill="#e8edf2"/>
  <rect x="${margin.left}" y="${y + 8}" width="${barWidth}" height="26" rx="3" fill="${color}"/>
  <text x="${margin.left + Math.max(barWidth, 0) + 10}" y="${y + 27}" font-size="14" fill="#243044">${value}</text>`;
    })
    .join("");

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
  <rect width="100%" height="100%" fill="#ffffff"/>
  <text x="32" y="42" font-size="24" font-family="Microsoft YaHei, sans-serif" font-weight="600" fill="#172033">${escapeXml(chartConfig.title)}</text>
  <g font-family="Microsoft YaHei, sans-serif">${rows}</g>
  <text x="${margin.left}" y="${height - 18}" font-size="12" fill="#667085">Generated by ArgSRE</text>
</svg>`;
}

export function buildReportPackage(records, config, options = {}) {
  const report = assembleReport(records);
  const chartSvg = renderBarChart(records, config.chart);
  const statusSummary = Object.entries(report.statusCounts)
    .map(([status, count]) => `${status}: ${count}`)
    .join("，");
  const detailRows = report.records
    .map(
      (record) =>
        `- ${record.serviceName}: 状态=${record.status}，实例=${record.instanceCount}，告警=${record.alarmCount}`,
    )
    .join("\n");
  const markdown = `# ${config.title}

- 生成时间：${report.generatedAt}
- 服务数量：${report.serviceCount}
- 实例总数：${report.totalInstances}
- 告警总数：${report.totalAlarms}
- 状态分布：${statusSummary || "无"}

## 服务明细

${detailRows || "- 无数据"}
`;
  const trend = options.trend;
  const trendSection =
    trend?.series?.length > 0
      ? `\n## ${trend.title}\n\n- 时间点数量：${trend.series.length}\n- 最新值：${trend.series.at(-1)?.[trend.valueField] ?? 0}\n`
      : "";
  const warningSection =
    options.warnings?.length > 0
      ? `\n## 数据源告警\n\n${options.warnings.map((warning) => `- ${warning}`).join("\n")}\n`
      : "";
  const completeMarkdown = `${markdown}${trendSection}${warningSection}`;

  return {
    report,
    markdown: completeMarkdown,
    chartSvg,
    message: {
      type: "daily_sre_report",
      title: config.title,
      generatedAt: report.generatedAt,
      summary: {
        serviceCount: report.serviceCount,
        totalInstances: report.totalInstances,
        totalAlarms: report.totalAlarms,
        statusCounts: report.statusCounts,
        warningCount: options.warnings?.length ?? 0,
      },
      warnings: options.warnings ?? [],
      markdown: completeMarkdown,
      chart: {
        fileName: "daily-report.svg",
        mimeType: "image/svg+xml",
        contentBase64: Buffer.from(chartSvg, "utf8").toString("base64"),
      },
      trendChart: trend?.chartSvg
        ? {
            fileName: "trend-chart.svg",
            mimeType: "image/svg+xml",
            contentBase64: Buffer.from(trend.chartSvg, "utf8").toString(
              "base64",
            ),
          }
        : undefined,
    },
  };
}
