function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function dayKey(timestamp) {
  return timestamp.slice(0, 10);
}

export function buildDailyTrend(snapshots) {
  const byDay = new Map();
  for (const snapshot of snapshots) {
    const day = dayKey(snapshot.timestamp);
    const current = byDay.get(day) ?? {
      day,
      snapshotCount: 0,
      serviceCount: 0,
      totalInstances: 0,
      totalAlarms: 0,
    };
    current.snapshotCount += 1;
    current.serviceCount = snapshot.records.length;
    current.totalInstances = snapshot.records.reduce(
      (sum, record) => sum + Number(record.instanceCount ?? 0),
      0,
    );
    current.totalAlarms = snapshot.records.reduce(
      (sum, record) => sum + Number(record.alarmCount ?? 0),
      0,
    );
    byDay.set(day, current);
  }
  return [...byDay.values()].sort((left, right) =>
    left.day.localeCompare(right.day),
  );
}

export function renderTrendChart(series, config) {
  const width = 920;
  const height = 360;
  const margin = { top: 72, right: 54, bottom: 68, left: 72 };
  const chartWidth = width - margin.left - margin.right;
  const chartHeight = height - margin.top - margin.bottom;
  const valueField = config.valueField;
  const values = series.map((point) => Number(point[valueField] ?? 0));
  const maxValue = Math.max(...values, 1);
  const xStep = series.length <= 1 ? 0 : chartWidth / (series.length - 1);
  const points = series.map((point, index) => {
    const x = margin.left + index * xStep;
    const y =
      margin.top +
      chartHeight -
      (Number(point[valueField] ?? 0) / maxValue) * chartHeight;
    return { ...point, x, y };
  });
  const polyline = points.map((point) => `${point.x},${point.y}`).join(" ");
  const labels = points
    .map(
      (point) => `
  <circle cx="${point.x}" cy="${point.y}" r="5" fill="#176b58"/>
  <text x="${point.x}" y="${point.y - 12}" text-anchor="middle" font-size="13" fill="#243044">${point[valueField]}</text>
  <text x="${point.x}" y="${height - 34}" text-anchor="middle" font-size="12" fill="#667085">${escapeXml(point.day.slice(5))}</text>`,
    )
    .join("");

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
  <rect width="100%" height="100%" fill="#ffffff"/>
  <text x="32" y="42" font-size="24" font-family="Microsoft YaHei, sans-serif" font-weight="600" fill="#172033">${escapeXml(config.title)}</text>
  <line x1="${margin.left}" y1="${margin.top + chartHeight}" x2="${width - margin.right}" y2="${margin.top + chartHeight}" stroke="#b8c2cc"/>
  <line x1="${margin.left}" y1="${margin.top}" x2="${margin.left}" y2="${margin.top + chartHeight}" stroke="#b8c2cc"/>
  <polyline points="${polyline}" fill="none" stroke="#176b58" stroke-width="4" stroke-linejoin="round" stroke-linecap="round"/>
  <g font-family="Microsoft YaHei, sans-serif">${labels}</g>
  <text x="${margin.left}" y="${height - 10}" font-size="12" fill="#667085">Generated by ArgSRE</text>
</svg>`;
}
